### ISSUE TITLE
Creating a custom browser implementation does not work

### ISSUE THREAD

**Issue by david-apples** [Frameworkium/frameworkium-core#104]
An attempt was made to create a edge custom browser implementation as follows as below:

```java
public class EdgeImpl extends AbstractDriver
{

    @Override
    public EdgeOptions getCapabilities()
    {
        EdgeOptions edgeOptions = new EdgeOptions();
        edgeOptions.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
        edgeOptions.setCapability("requireWindowFocus", true);
        return edgeOptions;
    }

    @Override
    public WebDriver getWebDriver(Capabilities capabilities)
    {
        final EdgeOptions edgeOptions;
        if (capabilities instanceof EdgeOptions)
        {
            edgeOptions = (EdgeOptions) capabilities;
        }
        else
        {
            edgeOptions = new EdgeOptions().merge(capabilities);
        }
        return new EdgeDriver(edgeOptions);
    }
}
```

This file was including in the utils folder of the test repo.

However on attempt to use it with the below command:

`mvn install verify -Denvironment=${Environment_SA} -DcustomBrowserImpl=EdgeImpl -P smoke-tests -pl test-smoke -DvideoCaptureUrl=http://${SLAVE_IP}:3000/download_video/%s.mp4  -Dsurefire.suiteXmlFiles=testsuite/SampleSingleTest.xml -DgridURL=http://${SLAVE_IP}:4444/wd/hub -am`

An error was generated:

```
FAILED CONFIGURATION: @BeforeMethod instantiateDriverObject
java.lang.IllegalArgumentException: Problem loading custom browser implementation: EdgeImpl
        at com.frameworkium.core.ui.driver.DriverSetup.lambda$getCustomBrowserImpl$1(DriverSetup.java:165)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.frameworkium.core.ui.driver.DriverSetup.getCustomBrowserImpl(DriverSetup.java:165)
        at com.frameworkium.core.ui.driver.DriverSetup.createDriverImpl(DriverSetup.java:88)
        at com.frameworkium.core.ui.driver.DriverSetup.instantiateDriver(DriverSetup.java:39)
        at com.frameworkium.core.ui.tests.BaseTest.instantiateDriverObject(BaseTest.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:516)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Creating a custom browser implementation as documented: https://frameworkium.github.io/#_pages/Custom-Browser-Implementations.md

No longer seems to work.

**Comment by ham1** [comment]
Do you have the EdgeDriver on your path? If not, could you try setting `-Dwebdriver.edge.driver=path/to/edge/driver.exe`

**Comment by david-apples** [comment]
Hi Ham : )

So I am running on windows 7 with a windows 10 VM with edge. The windows 10 VM is running selenium server using this command:

java -Dwebdriver.edge.driver=C:\Selenium\IEDriver\MicrosoftWebDriver.exe -jar C:\Selenium\selenium-server-standalone-3.11.0.jar

On the windows 7 machine I run my maven build with the ${SLAVE_IP} value above set to the ip of my VM. When I set -Dbrowser to chrome on my maven test build it did actually start edge on the windows 10 VM when the test began (and then fell over as it was using the chrome Impl) This at least indicates connection wise it seems to be working.

However trying to use my custom implementation it breaks before it even tries to connect,

**Comment by ham1** [comment]
Is this still an issue? If so I will look into it in the next few days.

**Comment by ham1** [comment]
Closing, please re-open if this is still an issue.
